menu:
    首页: http://www.monster1935.site
    Blog: http://www.monster1935.site/blog/
    实验室: http://www.monster1935.site/lab/
favicon: /small-logo.png
logo: http://oe7c74ud3.bkt.clouddn.com/logo.png
name: monster1935的博客

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
netease:

# Analytics
# google-analytics:
ga:

# about Infomation

about: 前端开发者@monster1935

# contact me ways and icons
way:
    Github: http://github.com/monster1935
    Segment: https://segmentfault.com/u/monster1935
    Weibo: http://weibo.com/monster1935
    Mail: mailto://liyb2014@163.com

icon:
    Github: icon-github
    Weibo: icon-weibo
    Segment: icon-sf
    Mail: icon-mail

# Copyright Infomation
startyear: 2015
